version: '2'
services:
  zimbra:
    build: docker
    image: tetatetit/zimbra
    volumes:
      - data:/var/lib/zimbra
    environment:
      PASSWORD: 'changeit'
    ports:
      - '25:25'
      - '456:456'
      - '587:587'
      - '110:110'
      - '143:143'
      - '993:993'
      - '995:995'
      - '443:443'
      - '8080:8080'
      - '8443:8443'
      - '7071:7071'
      - '9071:9071'
    networks:
      mysql:
        aliases:
          - mail
    restart: always
    domainname: tetatet.it
    hostname: zimbra
    dns:
    - 127.0.0.1
    - 127.0.0.11
    - 8.8.8.8
    - 8.8.4.4
    - 4.4.4.4
volumes:
  data:
    driver: local
networks:
  mysql:
    external:
      name: mysql_default
