#!/bin/bash

export IMAGE_IN=php
export IMAGE_OUT=tetatetit/php
export NOEDIT_MSG=`cat <<END
# Autogenerated by update.sh
# DO NOT EDIT IT DIRECTLY
END`

[[ $1 == --clean-configs ]] && CLEAN=yes

function gen {
  export TAG=$2
  DIR=$1
  [ $CLEAN ] && rm -rf $DIR/$TAG
  [ ! -d $TAG ] && mkdir -p $DIR/$TAG
  Dockerfile.tpl > $DIR/$TAG/Dockerfile
  $DIR/docker-compose.yml.tpl > $DIR/$TAG/docker-compose.yml
  $DIR/docker-compose.override.yml.tpl > $DIR/$TAG/docker-compose.override.yml
  [ ! -f $DIR/$TAG/config.yml ] && $DIR/config.yml.tpl > $DIR/$TAG/config.yml
}

gen php 7.1-apache
gen php 7.1-fpm
gen php 7.0-apache
gen php 7.0-fpm
gen php 5.6-apache
gen php 5.6-fpm

