version: '2'
services:
  mysql:
    image: mariadb
    volumes:
      - data:/var/lib/mysql
    restart: always
  myadmin:
    extends:
      file: config.yml
      service: myadmin
    image: tetatetit/myadmin
    depends_on:
      - mysql
    ports:
     - 3306:80
    environment:
      PMA_HOST: mysql
    restart: always

